### ISSUE TITLE
password for encrypted device

### ISSUE THREAD

**Issue by stefan-it** [yuvadm/amenthes#7]
For the `build.sh` script, it would be a great idea to extend the *General options* to a kind of password phrase (new argument or via read command). If no password was set a bit more secure one could be generated e.g. with:

```
cat /dev/urandom | tr -dc _A-Z-a-z-0-9_\?\! | head -c20
```

After image creation that new generated password can be printed out.

**Comment by yuvadm** [comment]
This is actually an easy fix, and desperately needed - there's no way to specify passphrase right now, just a placeholder.

Would you like to submit a pull request? :)

**Comment by ghost** [comment]
Thanks for accepting the [pull request](https://github.com/yuvadm/amenthes/pull/8)!
